# File: .github/workflows/workflow.yml

on: 
  workflow_dispatch: 

name: Run Azure Login With a Service Principal Secret

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
          az account show
    - name: Create AKS Cluster
      uses: azure/arm-deploy@v1
      with:
        resourceGroupName: dev-mohini-poc
        template: ./bicep/templates/aks-dev-template.bicep
        parameters: ./bicep/parameters/aks-dev-parameters.json