# File: .github/workflows/workflow.yml
on:
  workflow_dispatch:
    inputs:
      operation:
        type: choice
        options:
          - create
          - delete
name: AKS Cluster Operations
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      name: Code checkout
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
          az account show
    - name: Create AKS Cluster
      uses: azure/arm-deploy@v1
      if: github.event.inputs.operation == 'create'
      with:
        resourceGroupName: dev-mohini-poc
        template: ./bicep/templates/aks-dev-template.bicep
        parameters: ./bicep/parameters/aks-dev-parameters.json
    - name: Delete AKS Cluster
      if: github.event.inputs.operation == 'delete'
      run: |
        az aks delete --name mohini-poc --resource-group dev-mohini-poc --yes --no-wait